### ISSUE TITLE
[Feature request] Remove error path prefix

### ISSUE THREAD

**Issue by KaKi87** [ajv-validator/ajv-errors#40]
Hello,

I have a schema like this :

```js
{
    type: 'object',
    required: ['mail'],
    properties: {
        mail: {
            type: 'string',
            format: 'email',
            errorMessage: 'INVALID_MAIL'
        }
    },
    errorMessage: {
        required: {
            mail: 'MISSING_MAIL'
        }
    }
}
```

When validation fails, the returned error will either be `body MISSING_MAIL` or `body/mail INVALID_MAIL`.

I would just like to have my custom message and only my custom message, which is either `MISSING_MAIL` or `INVALID_MAIL`, to be returned.

Thanks

**Comment by yaneony** [comment]
Upvoting this one. Very weird to have error message like:
`"message": "Body Parameter 'email' is not provided!, body/username Username is invalid, given '\"true1\"!'"`

**Comment by Uriel29** [comment]
Upvoting

**Comment by marvix** [comment]
Any update for this request?

**Comment by epoberezkin** [comment]
I think you might be conflating two different problems. The value of errorMessage is used as the value of the `message` property of error object without any prefix. The prefix you are referring to is probably added because you use `ajv.errorsText()` method - is that correct?

If so, the correct approach is to output errors from your application code and not to use ajv.errorsText() - it's there simply for simple logging, not for user facing errors.

**Comment by KaKi87** [comment]
I am using fastify.

https://www.fastify.io/docs/v2.13.x/Validation-and-Serialization/#schema-resolver

**Comment by epoberezkin** [comment]
This is something to propose to fastify then.

**Comment by kieded** [comment]
for anyone struggling with this - overiding the fastify default error handler is the fix

here's some hacky code that works

  ```
app.setErrorHandler(function (error, request, reply) {
    // Log error
    this.log.error(error);

    const err = error;
    if (error?.validation?.length) {
      err.message = error.validation[0].message;
    }
    // Send error response
    return reply.status(error.statusCode || 400).send(err);
  });
```
